services:
  ollama-proxy:
    build: .
    container_name: ollama-proxy
    environment:
      - DOCKER=true
    volumes:
      - "./data:/app/data"
    networks:
      - traefik-global

networks:
  traefik-global:
    external: true
