version: "3.8"

services:
  ollama-proxy:
    build: .
    networks:
      - traefik-global
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama-proxy.rule=PathPrefix(`/`)"
      - "traefik.http.services.ollama-proxy.loadbalancer.server.port=6754"

networks:
  traefik-global:
    external: true